plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    compileSdk 35

    defaultConfig {
        applicationId "com.example.firstscichartapp"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.2.0-rc02'
    }
    namespace 'com.example.firstscichartapp'
}

dependencies {

    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    def sciChart_version = "4.7.0.4901"
    def compose_ui = '1.8.3'

    // region Compose UI
    implementation "androidx.compose.material:material:$compose_ui"
    implementation "androidx.compose.animation:animation:$compose_ui"
    // Tooling support (Previews, etc.)
    implementation "androidx.compose.ui:ui-tooling:$compose_ui"

    implementation "com.google.android.material:compose-theme-adapter:1.2.1"

    // Declare SciChart libraries as module dependencies
    implementation (group: 'com.scichart.library', name: 'core', version: sciChart_version, ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'data', version: sciChart_version, ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'drawing', version: sciChart_version, ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'charting', version: sciChart_version, ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'charting3d', version: sciChart_version, ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'extensions', version: sciChart_version, ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'extensions3d', version: sciChart_version, ext: 'aar')
}