apply plugin: 'com.android.application'

android {
    compileSdkVersion 37

    defaultConfig {
        applicationId "com.scichart.tutorial1"
        minSdkVersion 21
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.scichart.tutorial'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'

    // Declare SciChart libraries as module dependencies
    implementation (group: 'com.scichart.library', name: 'core', version: "$sciChartVersion", ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'data', version: "$sciChartVersion", ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'drawing', version: "$sciChartVersion", ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'charting', version: "$sciChartVersion", ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'extensions', version: "$sciChartVersion", ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'charting3d', version: "$sciChartVersion", ext: 'aar')
    implementation (group: 'com.scichart.library', name: 'extensions3d', version: "$sciChartVersion", ext: 'aar')
}
